# Generated by Django 4.1.7 on 2023-04-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocks',
            name='block_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
